version: '3'
services:
  redis:
    image: bitnami/redis:7.0
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "127.0.0.1:6379:6379"
#    volumes:
#      - ../redis-data/data:/data
